name: lammps-deepmd
channels:
  - https://conda.deepmodeling.com
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - jupyterlab
  - deepmd-kit=*=*cpu
  - libdeepmd=*=*cpu
  - lammps
  - mdanalysis
  - nglview
